### ISSUE TITLE
Feature: User can view the home page

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/HYPE#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the home page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The home page will be displayed for the user that shows a carousel of images, a shop now button, and an About Us section.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/HYPE/assets/66459527/dbe95610-d21a-4833-9084-0dfa44509609)
![image](https://github.com/restropiajr/HYPE/assets/66459527/a32e78dc-1b8e-464f-bec0-1ac035c56dd6)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a navbar that shows toggler, logo, and shopping cart.
- [x] Create a sidebar menu that shows all page links.
- [x] Create carousel for images.
- [x] Create a link to product for "SHOP NOW".
- [x] Create a footer that has github logo, linkedin logo, store logo, and copyright information.
- [x ] Create a scroll up button.
