### ISSUE TITLE
Feature: User can delete products from the shopping cart

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/HYPE#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete products from the shopping cart.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The my cart page will be displayed for the user that information and will allow them to delete products.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/HYPE/assets/66459527/54377417-5bf7-42db-92d5-61995b540934)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a empty cart button.
- [x] Create fetch request to the back end to delete the entire cart.
- [x] Create fetch request to the front end to indicate the the entire cart was deleted.
- [x] Create a x button for each product.
- [x] Create fetch request to the front end to indicate the the product was deleted.
- [x] Ensure that the functionality is under useContext.
