### ISSUE TITLE
Feature: User can update the quantity of products in the shopping cart

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/HYPE#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can update the quantity of products in the shopping cart.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The my cart page will be displayed for the user that information and will allow them to update quantity of carted products.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/HYPE/assets/66459527/0b402d59-1e2a-4ad2-982d-6eebbab89e74)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an update select option.
- [x] Create an update button.
- [x] Create fetch request to the back end to update the product.
- [x] Create fetch request to the front end to indicate the the product was updated.
- [x] Ensure that the functionality is under useContext.
