### ISSUE TITLE
Feature: User can checkout products with a form from the shopping cart

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/HYPE#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can checkout products with a form from the shopping cart.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The my cart page will be displayed for the user that information and will allow them to checkout the carted products.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/HYPE/assets/66459527/0b402d59-1e2a-4ad2-982d-6eebbab89e74)
![image](https://github.com/restropiajr/HYPE/assets/66459527/2c7c0a70-385d-4398-a04f-21a580c43c5a)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a checkout button.
- [x] Create fetch to the back end to check out the cart using stripe API.
- [x] Create fetch request to the front end to give stripe url.
- [x] Ensure that the functionality is under useContext.
