### ISSUE TITLE
Feature: User can view the list of products

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/HYPE#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the list of products.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The home page will be displayed for the user that shows the products for the website.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/HYPE/assets/66459527/7ba60a42-ebb5-4ea5-9ea4-007dc8f63a1c)
![image](https://github.com/restropiajr/HYPE/assets/66459527/2f1a8147-cb02-4eae-a2ed-a417f1502d0b)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create fetch request to back end to fetch product data.
- [x] Create fetch request to front end to give product data.
- [x] Create a useEffect side effect load function to load product data.
