### ISSUE TITLE
Feature: User can view their shopping cart

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/HYPE#23]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their shopping cart.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The product details page will be displayed for the user that shows carted products.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Uploading image.png…]()

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create fetch request to back end to fetch cart data.
- [x] Create fetch request to front end to give cart data.
- [x] Create a useEffect side effect load function to load cart data.
