### ISSUE TITLE
Feature: User can view the disclaimer modal

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/HYPE#32]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the disclaimer modal.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The disclaimer modal will be displayed for the user at the initial mount of the website to confirm the that the website is for educational purposes only and to provide instructions for Stripe test checkout.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/HYPE/assets/66459527/fea66bf3-5458-47b3-aa22-924e32764e1f)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create disclaimer statement.
- [x] Create Stripe test checkout instructions
- [x] Ensure modal blocks website view until the "Accept" button is clicked.
