### ISSUE TITLE
Feature: User can log in to their account

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/HYPE#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log in to their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The login page will be displayed for the user that allows them to log in with their username and password.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/HYPE/assets/66459527/8d638ac3-f867-4a3d-9456-7ed93e6a71bb)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a form that takes username and password value inputs with a log in button for submitting.
- [x] Create fetch request to the back end to send over user information.
- [x] Create fetch request to the front end to give front end user token.
- [x] Create functionality using useContext to handle log in from App.js
- [x] Create functionality in App.js to check whether a user is logged in during the mounting phase of App.js
