### ISSUE TITLE
Feature: User can search through the list of products

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/HYPE#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search through the list of products.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The product page will be displayed for the user that shows a search bar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/HYPE/assets/66459527/6922f850-668c-4316-a9d0-235836ae1160)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create search function using includes method that checks for the name of a product in the array (products).
- [x] Create debouncing to delay the instance of searching the products to create a smoother experience for the user.
- [x] Create Loading spinner render during debouncing.
